version: '3'

services:

  receiver-service:
    container_name: receiver-service
    build: ./
    depends_on:
      - db

  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - ./migration/up:/docker-entrypoint-initdb.d
        - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mts
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:

